version: '2'

services:
  app:
    image: golang:1.22
    volumes:
      - .:/work
    working_dir: /work

  licensing:
    build:
      context: ./docker
      dockerfile: Dockerfile.license_finder
    volumes:
      - .:/work
    working_dir: /work
